---
- type: collection\.immutable\.Map\[String,String\]
  specAsParameter: []   #this hides the type from query and path parameter
  specAsProperty:
    type: object
    additionalProperties:
      type: string
- type: org.joda.time.DateTime   # see https://github.com/iheartradio/play-swagger/issues/140
  specAsParameter: []   #this hides the type from query and path parameter
  specAsProperty:
    type: string
    format: date-time
- type: uk\.gov\.hmrc\.emailaddress\.EmailAddress   # see https://github.com/iheartradio/play-swagger/issues/140
  specAsParameter: [ ]   #this hides the type from query and path parameter
  specAsProperty:
    type: string
- type: clientname   # see https://github.com/iheartradio/play-swagger/issues/140
  specAsParameter:
    - type: string
  specAsProperty:
    type: string
