---
openapi: 3.0.3
info:
  title: "Secure Message API"
consumes:
  - application/json
produces:
  - application/json
components:
  securitySchemes:
    bearerToken:
      type: http
      scheme: bearer
