resolvers += MavenRepository("HMRC-open-artefacts-maven2", "https://open.artefacts.tax.service.gov.uk/maven2")
resolvers += Resolver.url("HMRC-open-artefacts-ivy2", url("https://open.artefacts.tax.service.gov.uk/ivy2"))(
  Resolver.ivyStylePatterns)
resolvers += Resolver.typesafeRepo("releases")

addSbtPlugin("uk.gov.hmrc"       % "sbt-auto-build"        % "3.7.0")
addSbtPlugin("uk.gov.hmrc"       % "sbt-distributables"    % "2.1.0")
addSbtPlugin("uk.gov.hmrc"       % "sbt-service-manager"   % "0.8.0")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"            % "2.8.13")
addSbtPlugin("com.iheart"        % "sbt-play-swagger"      % "0.10.8")
addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"          % "1.16")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"         % "2.0.0")
addSbtPlugin("org.scalastyle"    % "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("uk.gov.hmrc"       % "sbt-bobby"             % "3.3.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"           % "0.5.3")
